version: "3"
services:
  service:
    build:
      context: .
      args:
        env: "production"
    ports:
      - "444:444"
    volumes:
      - /apps/logs/service:/app/log:rw
      - /apps/certs/gorilla.lk:/apps/certs/gorilla.lk:ro
