
// -- META CITIES

db.getCollection('metacities').deleteMany({})
db.getCollection( 'metacities' ).insertMany( [
    { "name": "Colombo" },
    { "name": "Gampaha" },
    { "name": "Kurunegala" },
    { "name": "Kandy" },
    { "name": "Matale" },
    { "name": "Nuwara Eliya" },
    { "name": "Badulla" },
    { "name": "Galle" },
    { "name": "Matara" },
    { "name": "Hambantota" },
    { "name": "Ratnapura" },
    { "name": "Anuradhapura" },
    { "name": "Jaffna" },
    { "name": "Batticaloa" },
    { "name": "Ampara" },
    { "name": "Kalutara" },
    { "name": "Puttalam" },
    { "name": "Kegalle" },
    { "name": "Trincomalee" },
    { "name": "Mannar" },
    { "name": "Vavuniya" }
] );


db.getCollection( 'metasectors' ).deleteMany( {} )
db.getCollection( 'metasectors' ).insertMany( [
{ "name" : "Automotive/Automobile/AncillariesBanking/Accounting/Financial Services" },
{ "name" : "Bio TechnologyChemicals and Petrochem" },
{ "name" : "Construction & EngineeringFMCG" },
{ "name" : "Customer ServiceEducation" },
{ "name" : "Electronics ManufacturingEntertainment/Media/Publishing" },
{ "name" : "InsuranceITES and BPO" },
{ "name" : "IT/Computers - Hardware & NetworkingIT/Computers - Software" },
{ "name" : "KPO/Research/AnalyticsMachinery/Equipment Mfg." },
{ "name" : "Oil/Gas/PetroleumPharmaceuticals" },
{ "name" : "Plastic/RubberPower and Energy" },
{ "name" : "Real EstateRecruitment and Staffing" },
{ "name" : "RetailingSemiconductor Manufacturing" },
{ "name" : "Telecom" },
{ "name" : "Advertising/PR/Events" },
{ "name" : "Agriculture/Dairy/Forestry/Fishing" },
{ "name" : "Airlines/Aviation/Aerospace" },
{ "name" : "Alternate Energy" },
{ "name" : "Wellness/Fitness/Sports" },
{ "name" : "Beverages/Liquor" },
{ "name" : "Cement/Concrete/Readymix" },
{ "name" : "Ceramics & Sanitary Ware" },
{ "name" : "Comodities Trading" },
{ "name" : "Consulting/Advisory Services" },
{ "name" : "Courier/Freight/Transportation" },
{ "name" : "Internet/E-commerce" },
{ "name" : "Electrical/Switchgears" },
{ "name" : "Environmental Service" },
{ "name" : "Facility management" },
{ "name" : "Fertilizer/Pesticides" },
{ "name" : "Food & Packaged Food" },
{ "name" : "Textiles/Yarn/Fabrics/Garments" },
{ "name" : "Gems & Jewellery" },
{ "name" : "Glass" },
{ "name" : "Government / Public Sector/ Defence" },
{ "name" : "Consumer Electronics/Durables/Appliances" },
{ "name" : "Hospitals/Healthcare/Diagnostics" },
{ "name" : "Heat Ventilation Air Conditioning (HVAC)" },
{ "name" : "Catering/Hospitality" },
{ "name" : "General Trading/Import/Export" },
{ "name" : "Iron/Steel" },
{ "name" : "Internet Service Provider" },
{ "name" : "Law Enforcement/Security Services" },
{ "name" : "Leather" },
{ "name" : "Maritime Transportation" },
{ "name" : "Market Research" },
{ "name" : "Medical Transcription" },
{ "name" : "Mining" },
{ "name" : "Railways Speciality/Infrastructure" },
{ "name" : "NGO/Social Services" },
{ "name" : "Non-Ferrous Metals (Aluminium/Zinc etc.)" },
{ "name" : "Office Equipment/Automation" },
{ "name" : "Paints" },
{ "name" : "Paper" },
{ "name" : "Printing/Packaging" },
{ "name" : "Public Relations (PR)" },
{ "name" : "Shipping/Marine Services" },
{ "name" : "Social Media" },
{ "name" : "Travel/Tourism" },
{ "name" : "Tyres" },
{ "name" : "WoodOther" },
{ "name" : "Other " } ] );